language: java
jdk:
- oraclejdk8
script:
- mvn clean compile
- mvn test
- ./bin/rdflint.sh -check ontologies/*.ttl -assume import/*.ttl
- "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && [ ${TRAVIS_BRANCH} = 'master' ] && mvn package -DskipTests deploy:deploy-file -DrepositoryId=ossrh -Dfile=target/omnlib.jar -Durl=https://oss.sonatype.org/content/repositories/snapshots  -DgroupId=info.open-multinet -DartifactId=omnlib -Dversion=0.0.1-SNAPSHOT --settings .travis/settings.xml"
notifications:
  email:
  - alexander.willner@tu-berlin.de
  - fiteagle.dev@av.tu-berlin.de
  slack:
    secure: AU96qD4XI+McpOoyqaFRcDplDb1UR6iB6jE+WAzHmo6NIms469j2PiaKny3THz6AWIg9HChWyGv2yHQfxRuBx/0aPYhu0SI5Hggta6Iib29VAwZ/zMsD3vhANYW0js9X6nDdJQx9RMniJ023A3nO22q4Zyv/D1Fri63BQVSlipA=
cache:
  directories:
  - $HOME/.m2
after_success:
- mvn clean test jacoco:report coveralls:report
